// <auto-generated />
using Docius.Repository.Docius;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Docius.API.Migrations.Docius
{
    [DbContext(typeof(DociusContext))]
    [Migration("20250219234712_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Docius.Repository.Entities.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoImagem1")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("caminho_imagem_1");

                    b.Property<string>("CaminhoImagem2")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("caminho_imagem_2");

                    b.Property<string>("CaminhoLogo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("caminho_logo");

                    b.Property<string>("Dominio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dominio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("empresas");
                });
#pragma warning restore 612, 618
        }
    }
}
