# fly.toml app configuration file generated for docius-api-python on 2025-05-12T22:04:45-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'docius-api-python'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1024mb'
  cpu_kind = 'shared'
  cpus = 2
