services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=docius
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    restart: always

